-- Migration: Driver HR profiles for Ronyx HR module
CREATE TABLE IF NOT EXISTS public.driver_hr_profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  driver_id uuid REFERENCES public.drivers(id) ON DELETE CASCADE,
  organization_id uuid,
  cdl_copy_uploaded boolean DEFAULT false,
  medical_certificate_uploaded boolean DEFAULT false,
  drug_test_pre_employment boolean DEFAULT false,
  drug_test_random boolean DEFAULT false,
  drug_test_post_accident boolean DEFAULT false,
  safety_training_completed boolean DEFAULT false,
  safety_training_date date,
  hos_training_date date,
  hazmat_training_date date,
  fmcsa_clearinghouse_consent boolean DEFAULT false,
  assigned_vehicle_vin text,
  assigned_vehicle_unit text,
  trailer_numbers text,
  equipment_inspection_logs text,
  mileage_reports text,
  accident_report_history text,
  pay_rate_type text,
  pay_rate_amount numeric(10,2),
  deductions text,
  tax_info text,
  overtime_tracking boolean DEFAULT false,
  benefits text,
  paid_time_off text,
  accident_details text,
  tickets_violations text,
  safety_meeting_attendance text,
  corrective_actions text,
  employment_contract_signed boolean DEFAULT false,
  non_compete_signed boolean DEFAULT false,
  background_check_completed boolean DEFAULT false,
  drug_policy_ack boolean DEFAULT false,
  handbook_ack boolean DEFAULT false,
  review_date date,
  reviewer text,
  driver_scorecard text,
  improvement_plan text,
  disciplinary_actions text,
  application_date date,
  referral_source text,
  prehire_checklist_complete boolean DEFAULT false,
  orientation_date date,
  orientation_trainer text,
  road_test_result text,
  road_test_date date,
  termination_date date,
  termination_reason text,
  equipment_returned text,
  exit_interview_notes text,
  final_paycheck_issued boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_driver_hr_profiles_driver
  ON public.driver_hr_profiles(driver_id);

CREATE INDEX IF NOT EXISTS idx_driver_hr_profiles_org
  ON public.driver_hr_profiles(organization_id);
