-- Migration: Aggregate material & rate profiles for Ronyx aggregates module
CREATE TABLE IF NOT EXISTS public.aggregate_material_profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid,
  material_type text,
  material_code text,
  material_description text,
  supplier_location text,
  material_category text,
  stockpile_location text,
  availability_inventory text,
  rate_type text,
  base_rate numeric(10, 2),
  fuel_surcharge numeric(10, 2),
  delivery_charge numeric(10, 2),
  minimum_load_charge numeric(10, 2),
  brokered_load_pct numeric(6, 2),
  customer_specific_rates text,
  effective_start_date date,
  effective_end_date date,
  customer_name text,
  job_name text,
  job_site_address text,
  contact_person text,
  contact_number text,
  billing_terms text,
  customer_notes text,
  truck_type text,
  truck_assigned text,
  driver_assigned text,
  pickup_location text,
  delivery_location text,
  hauling_distance numeric(10, 2),
  estimated_load_time time,
  estimated_unload_time time,
  ticket_number text,
  tare_weight numeric(10, 2),
  gross_weight numeric(10, 2),
  net_weight numeric(10, 2),
  digital_ticket_uploads boolean DEFAULT false,
  gps_tracking boolean DEFAULT false,
  signature_capture boolean DEFAULT false,
  auto_invoice boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_aggregate_material_profiles_org
  ON public.aggregate_material_profiles(organization_id);
