-- Migration: Driver profiles for Ronyx driver module
CREATE TABLE IF NOT EXISTS public.driver_profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  driver_id uuid REFERENCES public.drivers(id) ON DELETE CASCADE,
  organization_id uuid,
  full_name text,
  photo_url text,
  date_of_birth date,
  phone text,
  email text,
  address text,
  emergency_contact_name text,
  emergency_contact_phone text,
  license_number text,
  license_state text,
  license_class text,
  license_expiration_date date,
  cdl_endorsements text,
  cdl_restrictions text,
  hire_date date,
  status text,
  position_role text,
  supervisor_name text,
  pay_rate numeric(10,2),
  mileage_rate numeric(10,2),
  cdl_copy_url text,
  medical_card_url text,
  work_authorization_url text,
  drug_test_results_url text,
  background_check_url text,
  training_certificates_url text,
  assigned_truck_number text,
  vehicle_vin text,
  license_plate text,
  equipment_type text,
  maintenance_history text,
  hos_logs text,
  eld_records text,
  inspection_reports text,
  violations text,
  orientation_completed boolean DEFAULT false,
  hazmat_training boolean DEFAULT false,
  safety_meetings_attendance text,
  certification_renewal_dates text,
  accidents_summary text,
  incident_photos_url text,
  incident_resolution text,
  dvir_reports text,
  repairs_requested_completed text,
  preventive_maintenance_schedule text,
  miles_driven numeric(10,2),
  pay_period_earnings numeric(12,2),
  deductions numeric(12,2),
  bonuses_reimbursements numeric(12,2),
  driver_scorecard text,
  disciplinary_actions text,
  recognition_awards text,
  supervisor_notes text,
  communication_log text,
  hr_dispatch_updates text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_driver_profiles_driver
  ON public.driver_profiles(driver_id);

CREATE INDEX IF NOT EXISTS idx_driver_profiles_org
  ON public.driver_profiles(organization_id);
