-- Migration 148: Bulk seed OO companies extracted from dispatch CSV (June 2026)
-- Safe insert: skips any company_name that already exists (case-insensitive match)

INSERT INTO ronyx_owner_operators (company_name, status, created_at, updated_at)
SELECT t.company_name, 'active', now(), now()
FROM (VALUES
  ('1974 Trucking LLC'),
  ('Agudelos Trucking LLC'),
  ('Akin Trading LLC'),
  ('All City Trucking LLC'),
  ('Always Ready Transport LLC'),
  ('At Water Trucking LLC'),
  ('Brinks Transport LLC'),
  ('California Auto Factory LLC'),
  ('Cesar Lira Trucking LLC'),
  ('Chavez Transport LLC'),
  ('Conquista Trucking LLC'),
  ('Dane Transportation Company LLC'),
  ('DD Express Solution Corp'),
  ('De Armas Dumps LLC'),
  ('DIAZ TRUCKING OF NAPLES INC'),
  ('Disaster Recovery Logistics LLC'),
  ('DMZ Rentals LLC'),
  ('Double F Transport'),
  ('El Shaddai Trucking'),
  ('EPM Trucking LLC'),
  ('Fournier Trucking Corp'),
  ('G&D Alliance LLC'),
  ('G&Solis Trucking LLC'),
  ('Gen Transport Corp'),
  ('Giang Trucking LLC'),
  ('Golden Route Logistics INC'),
  ('GRIT Logistics LLC'),
  ('H&F Trucking LLC'),
  ('Indy Dump Trucks LLC'),
  ('IPJ Enterprises'),
  ('Isaac''s Trucking LLC'),
  ('J Iraheta Trucking Corp'),
  ('J&M Tranz Corp'),
  ('Joe Express LLC'),
  ('JPD Hauling LLC'),
  ('Kaia Trucking LLC'),
  ('k&CQ Express LLC'),
  ('Landrove Trucking Inc'),
  ('LB Trucking'),
  ('Leah Trucking Inc'),
  ('Lemus Vargas Trucking LLC'),
  ('LGH Transport Corp'),
  ('Lyly Truck Services LLC'),
  ('Mangle Dump Truck LLC'),
  ('MAURICIO AREVALO MAO LOGISTICS CORP'),
  ('Mb Tk LLC'),
  ('MGSF Trucking Corporation'),
  ('Midwest Logistics Services LLC'),
  ('Mio Trucking Inc'),
  ('Misty Blue Trucking'),
  ('MSM Demolition LLC'),
  ('Naples Trucking Service Inc'),
  ('Nelle Transport LLC'),
  ('Newton Hauling LLC'),
  ('Oivatco Trucking LLC'),
  ('Olg Express LLC'),
  ('Olivas Services LLC'),
  ('OPR Hauling LLC'),
  ('Panter Trucking'),
  ('Pineda Commodity LLC'),
  ('Preferred Services & Transport LLC'),
  ('Raidel Trucking Inc'),
  ('Rapidgo LLC'),
  ('Rayo Mcqueen Trucking LLC'),
  ('RF Truck'),
  ('Rfournier LLC'),
  ('RICHAR R & M RICHARD''S TRUCKING LLC'),
  ('RIVES RIVES RIVES TRUCKING'),
  ('Roberts Jr Homes Services'),
  ('Roliester Truck LLC'),
  ('Round Trip Truckers LLC'),
  ('Santoyos Logistics INC'),
  ('SAYN MANTILLA SAYN M TRUCKING INC'),
  ('Sg Nathan LLC'),
  ('Shawn Harris Trucking LLC'),
  ('Smj Hauling LLC'),
  ('Snappy Services Inc'),
  ('Strain Trucking LLC'),
  ('SUPERIOR TRANSPORT CARRIER'),
  ('Tabares & Family Trucking LLC'),
  ('Tarrero Trucking Services LLC'),
  ('TOP CHOICE TRUCKING LLC'),
  ('Triple J Trucking'),
  ('Uribe Bros Trucking INC'),
  ('Veloz Trucking LLC'),
  ('Ylg All About Trucking Corp'),
  ('YMR Trucking Service LLC')
) AS t(company_name)
WHERE NOT EXISTS (
  SELECT 1 FROM ronyx_owner_operators o
  WHERE lower(trim(o.company_name)) = lower(trim(t.company_name))
);
