-- ============================================================
-- Migration 182: Ronyx Seed Data
--
-- Seeds owner operators, trucks, drivers, and pit/job sites
-- for Ronyx. Safe to re-run (ON CONFLICT DO NOTHING).
-- ============================================================

DO $$
DECLARE
  v_org_id uuid;
BEGIN

  SELECT id INTO v_org_id
  FROM public.organizations
  WHERE lower(name) LIKE '%ronyx%'
     OR lower(organization_code) LIKE '%ronyx%'
     OR id = '00000000-0000-0000-0000-000000000001'
  ORDER BY
    CASE WHEN lower(name) LIKE '%ronyx%' OR lower(organization_code) LIKE '%ronyx%' THEN 0 ELSE 1 END
  LIMIT 1;

  IF v_org_id IS NULL THEN
    RAISE NOTICE 'Ronyx org not found — skipping seed.';
    RETURN;
  END IF;

  RAISE NOTICE 'Seeding Ronyx data for org: %', v_org_id;

  -- ─── OWNER OPERATORS ──────────────────────────────────────────────────
  -- Status inference:
  --   'active'   = Active Policy confirmed
  --   'pending'  = Sent agent/owner email, waiting on documents
  --   'inactive' = On hold, cancelled, expired
  --   'active'   = Default for known companies with no note

  INSERT INTO public.owner_operators (organization_id, company_name, status)
  VALUES
    (v_org_id, '1974 Trucking LLC',                          'active'),
    (v_org_id, 'A Lone Journey Transportation LLC',          'active'),
    (v_org_id, 'Active Society LLC',                         'active'),
    (v_org_id, 'Always Ready Transport LLC',                 'pending'),
    (v_org_id, 'At Water Trucking LLC',                      'active'),
    (v_org_id, 'Brinks Transport LLC',                       'pending'),
    (v_org_id, 'California Auto Factory LLC',                'active'),
    (v_org_id, 'Cesar Lira Trucking LLC',                    'active'),
    (v_org_id, 'Chavez Transport LLC',                       'pending'),
    (v_org_id, 'Dane Transportation Company LLC',            'active'),
    (v_org_id, 'DD Express Solution Corp',                   'active'),
    (v_org_id, 'Denesse Group Inc',                          'active'),
    (v_org_id, 'DMZ Rentals LLC',                            'active'),
    (v_org_id, 'Double F Transport',                         'active'),
    (v_org_id, 'El Shaddai Trucking',                        'active'),
    (v_org_id, 'Elvis Rodriguez - Ronyx Logistics',          'active'),
    (v_org_id, 'EPM Trucking LLC',                           'inactive'),
    (v_org_id, 'Fournier Trucking Corp',                     'active'),
    (v_org_id, 'G&S Solis Trucking LLC',                     'pending'),
    (v_org_id, 'G&D Alliance LLC',                           'active'),
    (v_org_id, 'Gen Transport Corp',                         'active'),
    (v_org_id, 'Giang Trucking LLC',                         'pending'),
    (v_org_id, 'Golden Route Logistics INC',                 'active'),
    (v_org_id, 'GRIT Logistics LLC',                         'pending'),
    (v_org_id, 'H&F Trucking LLC',                           'active'),
    (v_org_id, 'Indy Dump Trucks LLC',                       'active'),
    (v_org_id, 'Indy Independent Contractor Services LLC',   'active'),
    (v_org_id, 'IPJ Enterprises',                            'active'),
    (v_org_id, 'Isaac''s Trucking LLC',                      'active'),
    (v_org_id, 'J Iraheta Trucking Corp',                    'active'),
    (v_org_id, 'J&J Alvarado''s Trucking LLC',               'active'),
    (v_org_id, 'J&M Tranz Corp',                             'active'),
    (v_org_id, 'Joe Express LLC',                            'active'),
    (v_org_id, 'JPD Hauling LLC',                            'active'),
    (v_org_id, 'K&CQ Express LLC',                           'active'),
    (v_org_id, 'Kaia Trucking LLC',                          'active'),
    (v_org_id, 'Landrove Trucking Inc',                      'pending'),
    (v_org_id, 'LB Trucking',                                'active'),
    (v_org_id, 'Leah Trucking Inc.',                         'active'),
    (v_org_id, 'Lemus Vargas Trucking LLC',                  'pending'),
    (v_org_id, 'LGH Transport Corp',                         'pending'),
    (v_org_id, 'Lyly Truck Services LLC',                    'active'),
    (v_org_id, 'Mangle Dump Truck LLC',                      'active'),
    (v_org_id, 'MAO Logistics Corp',                         'active'),
    (v_org_id, 'Mb Tk LLC',                                  'active'),
    (v_org_id, 'MGSF Trucking Corporation',                  'inactive'),
    (v_org_id, 'Midwest Logistics Services LLC',             'active'),
    (v_org_id, 'Mio Trucking Inc',                           'active'),
    (v_org_id, 'Misty Blue Trucking',                        'active'),
    (v_org_id, 'Montes Trucking',                            'active'),
    (v_org_id, 'MSM Demolition LLC',                         'active'),
    (v_org_id, 'Naples Trucking Service Inc',                'pending'),
    (v_org_id, 'Nelle Transport LLC',                        'active'),
    (v_org_id, 'Newton Hauling LLC',                         'active'),
    (v_org_id, 'Oivatco Trucking LLC',                       'inactive'),
    (v_org_id, 'Olivas Services LLC',                        'active'),
    (v_org_id, 'Panter Trucking',                            'active'),
    (v_org_id, 'Pineda Commodity LLC',                       'active'),
    (v_org_id, 'Preferred Services & Transport LLC',         'active'),
    (v_org_id, 'Rayo Mcqueen Trucking LLC',                  'pending'),
    (v_org_id, 'Rfournier LLC',                              'pending'),
    (v_org_id, 'R & M Richard''s Trucking LLC',              'active'),
    (v_org_id, 'Rives Rives Trucking',                       'pending'),
    (v_org_id, 'Robert''s Jr Homes Services',                'active'),
    (v_org_id, 'Roliester Truck LLC',                        'pending'),
    (v_org_id, 'Round Trip Truckers LLC',                    'active'),
    (v_org_id, 'Santoyos Logistics INC',                     'active'),
    (v_org_id, 'SAYN M Trucking INC',                        'active'),
    (v_org_id, 'Sg Nathan LLC',                              'active'),
    (v_org_id, 'Shawn Harris Trucking LLC',                  'active'),
    (v_org_id, 'SMJ Hauling LLC',                            'active'),
    (v_org_id, 'Strain Trucking LLC',                        'active'),
    (v_org_id, 'Superior Transport Carrier',                 'active'),
    (v_org_id, 'Tabares & Family Trucking LLC',              'pending'),
    (v_org_id, 'Tarrero Trucking Services LLC',              'active'),
    (v_org_id, 'Top Choice Trucking LLC',                    'pending'),
    (v_org_id, 'Triple J Trucking',                          'active'),
    (v_org_id, 'Uribe Bros Trucking INC',                    'active'),
    (v_org_id, 'Veloz Trucking LLC',                         'active'),
    (v_org_id, 'YLG All About Trucking Corp',                'pending'),
    (v_org_id, 'YMR Trucking Service LLC',                   'active'),
    (v_org_id, 'AGA Trucking LLC',                           'pending'),
    (v_org_id, 'Agudelos Trucking LLC',                      'active'),
    (v_org_id, 'Akin Trading LLC',                           'active'),
    (v_org_id, 'All City Trucking LLC',                      'active'),
    (v_org_id, 'Conquista Trucking LLC',                     'active'),
    (v_org_id, 'De Armas Dumps LLC',                         'pending'),
    (v_org_id, 'DIAZ Trucking Of Naples INC',                'active'),
    (v_org_id, 'Disaster Recovery Logistics LLC',            'active'),
    (v_org_id, 'Snappy Services Inc.',                       'active'),
    (v_org_id, 'RF Truck',                                   'active'),
    (v_org_id, 'Raidel Trucking Inc',                        'pending'),
    (v_org_id, 'Rapidgo LLC',                                'pending'),
    (v_org_id, 'OPR Hauling LLC',                            'inactive'),
    (v_org_id, 'OLG Express LLC',                            'active')
  ON CONFLICT DO NOTHING;


  -- ─── TRUCKS ──────────────────────────────────────────────────────────

  INSERT INTO public.ronyx_trucks (organization_id, truck_number, status)
  VALUES
    (v_org_id, '8164',        'active'),
    (v_org_id, '8204',        'active'),
    (v_org_id, '7809',        'active'),
    (v_org_id, '8143',        'active'),
    (v_org_id, '8205',        'active'),
    (v_org_id, '7890',        'active'),
    (v_org_id, '7810',        'active'),
    (v_org_id, '8157',        'active'),
    (v_org_id, '8202',        'active'),
    (v_org_id, '8112',        'active'),
    (v_org_id, '8116',        'active'),
    (v_org_id, '8108',        'active'),
    (v_org_id, '8109',        'active'),
    (v_org_id, '7819',        'active'),
    (v_org_id, '7816',        'active'),
    (v_org_id, '8147',        'active'),
    (v_org_id, '001',         'active'),
    (v_org_id, '1236',        'active'),
    (v_org_id, '1237',        'active'),
    (v_org_id, '7960',        'active'),
    (v_org_id, '7967',        'active'),
    (v_org_id, '7979',        'active'),
    (v_org_id, '7980',        'active'),
    (v_org_id, '7983',        'active'),
    (v_org_id, '7984',        'active'),
    (v_org_id, '7988',        'active'),
    (v_org_id, '7995',        'active'),
    (v_org_id, '7997',        'active'),
    (v_org_id, '7999',        'active'),
    (v_org_id, '8026',        'active'),
    (v_org_id, '8052',        'active'),
    (v_org_id, '8053',        'active'),
    (v_org_id, '8054',        'active'),
    (v_org_id, '8058',        'active'),
    (v_org_id, '8063',        'active'),
    (v_org_id, '8075',        'active'),
    (v_org_id, '8082',        'active'),
    (v_org_id, '8083',        'active'),
    (v_org_id, '8088',        'active'),
    (v_org_id, '8089',        'active'),
    (v_org_id, '8104',        'active'),
    (v_org_id, '8105',        'active'),
    (v_org_id, '8106',        'active'),
    (v_org_id, '8107',        'active'),
    (v_org_id, '7817',        'active'),
    (v_org_id, '6580',        'active'),
    (v_org_id, '8132',        'active'),
    (v_org_id, '7796',        'active'),
    (v_org_id, '7859',        'active'),
    (v_org_id, '8126',        'active'),
    (v_org_id, '7778',        'active'),
    (v_org_id, '7782',        'active'),
    (v_org_id, '8179',        'active'),
    (v_org_id, '8219',        'active'),
    (v_org_id, '7799',        'active'),
    (v_org_id, '7846',        'active'),
    (v_org_id, '2T 57',       'active'),
    (v_org_id, '2T 58',       'active'),
    (v_org_id, '2T 59',       'active'),
    (v_org_id, 'C & A 777',   'active'),
    (v_org_id, 'Credence97',  'active'),
    (v_org_id, 'Credence98',  'active'),
    (v_org_id, 'DLT 715',     'active'),
    (v_org_id, 'GHC 007',     'active'),
    (v_org_id, 'GHC 42',      'active'),
    (v_org_id, 'GHC 55',      'active'),
    (v_org_id, 'GHC 7',       'active'),
    (v_org_id, 'GHC 74',      'active'),
    (v_org_id, 'GHC 77',      'active'),
    (v_org_id, 'GHC 89',      'active'),
    (v_org_id, 'GRIT 103',    'active'),
    (v_org_id, 'GRIT 104',    'active'),
    (v_org_id, 'GRIT 108',    'active'),
    (v_org_id, 'Kimard 618',  'active'),
    (v_org_id, 'Kimrad439',   'active'),
    (v_org_id, 'Kimrad630',   'active'),
    (v_org_id, 'Munoz 03',    'active'),
    (v_org_id, 'My Truck',    'active'),
    (v_org_id, 'RAP 150',     'active'),
    (v_org_id, 'Si Fuentes 43','active'),
    (v_org_id, 'T & H 18',    'active'),
    (v_org_id, '8019',        'active'),
    (v_org_id, '8028',        'active'),
    (v_org_id, '8029',        'active'),
    (v_org_id, '8045',        'active'),
    (v_org_id, '8046',        'active'),
    (v_org_id, '8048',        'active'),
    (v_org_id, '8049',        'active'),
    (v_org_id, '8050',        'active'),
    (v_org_id, '82 HF',       'active'),
    (v_org_id, '97HF',        'active'),
    (v_org_id, '8097',        'active'),
    (v_org_id, '7896',        'active'),
    (v_org_id, '7897',        'active'),
    (v_org_id, '7898',        'active'),
    (v_org_id, '7902',        'active'),
    (v_org_id, '8127',        'active'),
    (v_org_id, '8128',        'active'),
    (v_org_id, '8129',        'active'),
    (v_org_id, '8130',        'active'),
    (v_org_id, '8131',        'active'),
    (v_org_id, '7861',        'active'),
    (v_org_id, '7830',        'active'),
    (v_org_id, '7820',        'active'),
    (v_org_id, '7888',        'active'),
    (v_org_id, '7847',        'active'),
    (v_org_id, '8002',        'active'),
    (v_org_id, '8003',        'active'),
    (v_org_id, '8113',        'active'),
    (v_org_id, '7840',        'active'),
    (v_org_id, '8149',        'active'),
    (v_org_id, '8150',        'active'),
    (v_org_id, '8212',        'active'),
    (v_org_id, '8211',        'active'),
    (v_org_id, '7813',        'active'),
    (v_org_id, '7798',        'active'),
    (v_org_id, '7878',        'active'),
    (v_org_id, '7892',        'active'),
    (v_org_id, '8215',        'active'),
    (v_org_id, '8216',        'active'),
    (v_org_id, '8821',        'active'),
    (v_org_id, '8824',        'active'),
    (v_org_id, '8827',        'active'),
    (v_org_id, '8813',        'active'),
    (v_org_id, '8831',        'active'),
    (v_org_id, '7845',        'active'),
    (v_org_id, '7858',        'active'),
    (v_org_id, '7887',        'active'),
    (v_org_id, '7789',        'active'),
    (v_org_id, '7835',        'active'),
    (v_org_id, '7877',        'active'),
    (v_org_id, '7885',        'active'),
    (v_org_id, '7895',        'active'),
    (v_org_id, '8222',        'active'),
    (v_org_id, '8152',        'active'),
    (v_org_id, '8159',        'active'),
    (v_org_id, '8160',        'active'),
    (v_org_id, '8161',        'active'),
    (v_org_id, '8203',        'active'),
    (v_org_id, '8213',        'active'),
    (v_org_id, '8158',        'active'),
    (v_org_id, '7833',        'active'),
    (v_org_id, '7836',        'active'),
    (v_org_id, '7850',        'active'),
    (v_org_id, '7867',        'active'),
    (v_org_id, '7869',        'active'),
    (v_org_id, '7870',        'active'),
    (v_org_id, '7894',        'active'),
    (v_org_id, '7824',        'active'),
    (v_org_id, '8217',        'active'),
    (v_org_id, '8218',        'active'),
    (v_org_id, 'N101',        'active'),
    (v_org_id, 'N124',        'active'),
    (v_org_id, 'N41',         'active'),
    (v_org_id, '7805',        'active'),
    (v_org_id, '7969',        'active'),
    (v_org_id, '7970',        'active'),
    (v_org_id, '7971',        'active'),
    (v_org_id, '7829',        'active'),
    (v_org_id, '7978',        'active'),
    (v_org_id, '1510',        'active'),
    (v_org_id, '1422',        'active'),
    (v_org_id, '7879',        'active'),
    (v_org_id, '7855',        'active'),
    (v_org_id, '7880',        'active'),
    (v_org_id, '7886',        'active'),
    (v_org_id, '7790',        'active'),
    (v_org_id, '7791',        'active'),
    (v_org_id, '7792',        'active'),
    (v_org_id, '7864',        'active'),
    (v_org_id, '7780',        'active'),
    (v_org_id, '7781',        'active'),
    (v_org_id, '7862',        'active'),
    (v_org_id, '7863',        'active'),
    (v_org_id, '7904',        'active'),
    (v_org_id, '8221',        'active'),
    (v_org_id, '7806',        'active'),
    (v_org_id, '7783',        'active'),
    (v_org_id, '7905',        'active'),
    (v_org_id, '7873',        'active'),
    (v_org_id, '8162',        'active'),
    (v_org_id, '7866',        'active'),
    (v_org_id, '7853',        'active'),
    (v_org_id, '7776',        'active'),
    (v_org_id, '7812',        'active'),
    (v_org_id, '7801',        'active'),
    (v_org_id, '7985',        'active'),
    (v_org_id, '8153',        'active'),
    (v_org_id, '8220',        'active'),
    (v_org_id, '7793',        'active'),
    (v_org_id, '7876',        'active'),
    (v_org_id, '7881',        'active'),
    (v_org_id, '7900',        'active'),
    (v_org_id, '8151',        'active'),
    (v_org_id, '8142',        'active'),
    (v_org_id, '7831',        'active'),
    (v_org_id, '8138',        'active'),
    (v_org_id, '8137',        'active'),
    (v_org_id, '8062',        'active'),
    (v_org_id, '8065',        'active'),
    (v_org_id, '8073',        'active'),
    (v_org_id, '8030',        'active'),
    (v_org_id, '8064',        'active'),
    (v_org_id, '7795',        'active'),
    (v_org_id, '8201',        'active'),
    (v_org_id, '8154',        'active'),
    (v_org_id, '8155',        'active'),
    (v_org_id, '8200',        'active'),
    (v_org_id, '8210',        'active'),
    (v_org_id, '7976',        'active'),
    (v_org_id, '7977',        'active'),
    (v_org_id, '7857',        'active'),
    (v_org_id, '7854',        'active'),
    (v_org_id, '7856',        'active'),
    (v_org_id, '7821',        'active'),
    (v_org_id, '8145',        'active'),
    (v_org_id, '7844',        'active'),
    (v_org_id, '7848',        'active'),
    (v_org_id, '7851',        'active'),
    (v_org_id, '8163',        'active')
  ON CONFLICT DO NOTHING;


  -- ─── DRIVERS ─────────────────────────────────────────────────────────
  -- Format: "Last, First" → first_name, last_name
  -- Skips "???" and blank entries.

  INSERT INTO public.driver_profiles (organization_id, first_name, last_name, full_name, status)
  VALUES
    (v_org_id, 'Mark',        'Moore',              'Mark Moore',              'active'),
    (v_org_id, 'Carolyn',     'Bostick',            'Carolyn Bostick',         'active'),
    (v_org_id, 'Victor',      'Campos',             'Victor Campos',           'active'),
    (v_org_id, 'Miguel',      'Bugarin',            'Miguel Bugarin',          'active'),
    (v_org_id, 'Brandon',     'Roberts',            'Brandon Roberts',         'active'),
    (v_org_id, 'Jorge',       'Vazquez',            'Jorge Vazquez',           'active'),
    (v_org_id, 'Daniel',      'Villasenor Villasenor','Daniel Villasenor Villasenor','active'),
    (v_org_id, 'Xavier',      'Fields',             'Xavier Fields',           'active'),
    (v_org_id, 'Cesar',       'Lira',               'Cesar Lira',              'active'),
    (v_org_id, 'Juan',        'Pepi',               'Juan Pepi',               'active'),
    (v_org_id, 'Irving',      'Pepi',               'Irving Pepi',             'active'),
    (v_org_id, 'Oliver',      'Dane',               'Oliver Dane',             'active'),
    (v_org_id, 'Olivia',      'Dane',               'Olivia Dane',             'active'),
    (v_org_id, 'Fabio',       'Jimenez',            'Fabio Jimenez',           'active'),
    (v_org_id, 'Dennis',      'Aguilar',            'Dennis Aguilar',          'active'),
    (v_org_id, 'Anthony',     'Rogers',             'Anthony Rogers',          'active'),
    (v_org_id, 'Ricardo',     'Villalovos',         'Ricardo Villalovos',      'active'),
    (v_org_id, 'David',       'Trejo',              'David Trejo',             'active'),
    (v_org_id, 'Thomas',      'Trejo',              'Thomas Trejo',            'active'),
    (v_org_id, 'Rene',        'Dager',              'Rene Dager',              'active'),
    (v_org_id, 'Gregory',     'Huval',              'Gregory Huval',           'active'),
    (v_org_id, 'Aramis',      'Matamoros',          'Aramis Matamoros',        'active'),
    (v_org_id, 'Javier',      'Alonso',             'Javier Alonso',           'active'),
    (v_org_id, 'Francisco',   'Salcido',            'Francisco Salcido',       'active'),
    (v_org_id, 'David',       'Price',              'David Price',             'active'),
    (v_org_id, 'Guillermo',   'Alonso',             'Guillermo Alonso',        'active'),
    (v_org_id, 'Gavino',      'Olivas',             'Gavino Olivas',           'active'),
    (v_org_id, 'Apolinar',    'Adame',              'Apolinar Adame',          'active'),
    (v_org_id, 'Gabriel',     'Gomez',              'Gabriel Gomez',           'active'),
    (v_org_id, 'Javier',      'Lopez',              'Javier Lopez',            'active'),
    (v_org_id, 'Martin',      'Pedro',              'Martin Pedro',            'active'),
    (v_org_id, 'Juan',        'Escareno',           'Juan Escareno',           'active'),
    (v_org_id, 'Jose',        'Garcia',             'Jose Garcia',             'active'),
    (v_org_id, 'Francisco',   'Almanza',            'Francisco Almanza',       'active'),
    (v_org_id, 'Armando',     'Munos',              'Armando Munos',           'active'),
    (v_org_id, 'Manuel',      'Portillo',           'Manuel Portillo',         'active'),
    (v_org_id, 'Jonathan',    'Martinez',           'Jonathan Martinez',       'active'),
    (v_org_id, 'Carlos',      'Portillo',           'Carlos Portillo',         'active'),
    (v_org_id, 'Efren',       'Martinez',           'Efren Martinez',          'active'),
    (v_org_id, 'Eiby',        'Martinez',           'Eiby Martinez',           'active'),
    (v_org_id, 'Ismael',      'Olivas',             'Ismael Olivas',           'active'),
    (v_org_id, 'Reina',       'Marquez',            'Reina Marquez',           'active'),
    (v_org_id, 'David',       'Gonzalez',           'David Gonzalez',          'active'),
    (v_org_id, 'Vicente',     'Gallegos',           'Vicente Gallegos',        'active'),
    (v_org_id, 'Gerardo',     'Claudio',            'Gerardo Claudio',         'active'),
    (v_org_id, 'Elvis',       'Rodriguez',          'Elvis Rodriguez',         'active'),
    (v_org_id, 'Costantino',  'Ianni',              'Costantino Ianni',        'active'),
    (v_org_id, 'Delton',      'Pinder',             'Delton Pinder',           'active'),
    (v_org_id, 'Meredith',    'Walter',             'Meredith Walter',         'active'),
    (v_org_id, 'Carlos',      'Camara',             'Carlos Camara',           'active'),
    (v_org_id, 'Rolando',     'Garcia',             'Rolando Garcia',          'active'),
    (v_org_id, 'Rebin',       'Salej',              'Rebin Salej',             'active'),
    (v_org_id, 'Maikel',      'Rodriguez',          'Maikel Rodriguez',        'active'),
    (v_org_id, 'Dunian',      'Perez Mantilla',     'Dunian Perez Mantilla',   'active'),
    (v_org_id, 'Mike',        'Giang',              'Mike Giang',              'active'),
    (v_org_id, 'Henzo',       'Fernandez',          'Henzo Fernandez',         'active'),
    (v_org_id, 'Shallah',     'Gibson',             'Shallah Gibson',          'active'),
    (v_org_id, 'Carlos',      'Cabrera',            'Carlos Cabrera',          'active'),
    (v_org_id, 'Tim',         'Johnson',            'Tim Johnson',             'active'),
    (v_org_id, 'Cesar',       'Vargas',             'Cesar Vargas',            'active'),
    (v_org_id, 'Tim',         'Colbert',            'Tim Colbert',             'active'),
    (v_org_id, 'Ashley',      'Molina',             'Ashley Molina',           'active'),
    (v_org_id, 'Manuel',      'De La Torre',        'Manuel De La Torre',      'active'),
    (v_org_id, 'Pat',         'Hendrick',           'Pat Hendrick',            'active'),
    (v_org_id, 'Monte',       'Schaffer',           'Monte Schaffer',          'active'),
    (v_org_id, 'Jeffrey',     'Fortner',            'Jeffrey Fortner',         'active'),
    (v_org_id, 'Shawn',       'Ewing',              'Shawn Ewing',             'active'),
    (v_org_id, 'Codee',       'Bowman',             'Codee Bowman',            'active'),
    (v_org_id, 'Steve',       'Raus',               'Steve Raus',              'active'),
    (v_org_id, 'Robert',      'Wallen',             'Robert Wallen',           'active'),
    (v_org_id, 'Bo',          'Likes',              'Bo Likes',                'active'),
    (v_org_id, 'Derrick',     'Miller',             'Derrick Miller',          'active'),
    (v_org_id, 'Nathan',      'Stillwagon',         'Nathan Stillwagon',       'active'),
    (v_org_id, 'Armando',     'Martinez',           'Armando Martinez',        'active'),
    (v_org_id, 'Steven',      'Jones',              'Steven Jones',            'active'),
    (v_org_id, 'Analyssa',    'Mendoza',            'Analyssa Mendoza',        'active'),
    (v_org_id, 'Joel',        'Munoz',              'Joel Munoz',              'active'),
    (v_org_id, 'Brayan',      'Contreras',          'Brayan Contreras',        'active'),
    (v_org_id, 'Rafael',      'Para',               'Rafael Para',             'active'),
    (v_org_id, 'Jessie',      'Si Fuentes',         'Jessie Si Fuentes',       'active'),
    (v_org_id, 'Dakota',      'Lindsey',            'Dakota Lindsey',          'active'),
    (v_org_id, 'Luis',        'Diaz',               'Luis Diaz',               'active'),
    (v_org_id, 'Ramon',       'Peregrino',          'Ramon Peregrino',         'active'),
    (v_org_id, 'Jorge',       'Gallago',            'Jorge Gallago',           'active'),
    (v_org_id, 'Daniel',      'Gonzalez',           'Daniel Gonzalez',         'active'),
    (v_org_id, 'Augustine',   'Luera',              'Augustine Luera',         'active'),
    (v_org_id, 'Trace',       'Burkhalter',         'Trace Burkhalter',        'active'),
    (v_org_id, 'Nico',        'Gonzalez',           'Nico Gonzalez',           'active'),
    (v_org_id, 'Ricardo',     'Vasquez',            'Ricardo Vasquez',         'active'),
    (v_org_id, 'Juan',        'Garcia',             'Juan Garcia',             'active'),
    (v_org_id, 'Armando',     'Tinajero',           'Armando Tinajero',        'active'),
    (v_org_id, 'Timmie',      'Bradley',            'Timmie Bradley',          'active'),
    (v_org_id, 'Victor',      'Harris',             'Victor Harris',           'active'),
    (v_org_id, 'Michael',     'Mcallister',         'Michael Mcallister',      'active'),
    (v_org_id, 'Joyce',       'Finch',              'Joyce Finch',             'active'),
    (v_org_id, 'Kayla',       'Hayes',              'Kayla Hayes',             'active'),
    (v_org_id, 'Robert',      'Love',               'Robert Love',             'active'),
    (v_org_id, 'Dominique',   'King',               'Dominique King',          'active'),
    (v_org_id, 'Amber',       'Ricks',              'Amber Ricks',             'active'),
    (v_org_id, 'Martez',      'Lewis',              'Martez Lewis',            'active'),
    (v_org_id, 'Lorenzo',     'Carlos Gil Rodriguez','Lorenzo Carlos Gil Rodriguez','active'),
    (v_org_id, 'Leonardo',    'Garcia',             'Leonardo Garcia',         'active'),
    (v_org_id, 'Ruben',       'Molina',             'Ruben Molina',            'active'),
    (v_org_id, 'Eddy',        'Isaac',              'Eddy Isaac',              'active'),
    (v_org_id, 'Jose',        'Guzman',             'Jose Guzman',             'active'),
    (v_org_id, 'Benjamin',    'Adame',              'Benjamin Adame',          'active'),
    (v_org_id, 'Everly',      'Romero',             'Everly Romero',           'active'),
    (v_org_id, 'Jesus',       'Alvarado',           'Jesus Alvarado',          'active'),
    (v_org_id, 'Juan',        'Villarreal',         'Juan Villarreal',         'active'),
    (v_org_id, 'Jose',        'Ortiz',              'Jose Ortiz',              'active'),
    (v_org_id, 'Pedro',       'Malagon',            'Pedro Malagon',           'active'),
    (v_org_id, 'Alexander',   'Rodriguez',          'Alexander Rodriguez',     'active'),
    (v_org_id, 'Jorge',       'Perez',              'Jorge Perez',             'active'),
    (v_org_id, 'Yeinier',     'Quiones',            'Yeinier Quiones',         'active'),
    (v_org_id, 'Christopher', 'Howard',             'Christopher Howard',      'active'),
    (v_org_id, 'Richard',     'Zachary',            'Richard Zachary',         'active'),
    (v_org_id, 'Michel',      'Medina',             'Michel Medina',           'active'),
    (v_org_id, 'Shirley',     'Laudig',             'Shirley Laudig',          'active'),
    (v_org_id, 'Curt',        'Noel',               'Curt Noel',               'active'),
    (v_org_id, 'Ekar',        'Daniel',             'Ekar Daniel',             'active'),
    (v_org_id, 'Jorge',       'Olgin',              'Jorge Olgin',             'active'),
    (v_org_id, 'Jose',        'Flores',             'Jose Flores',             'active'),
    (v_org_id, 'Maiquel',     'Gonzalez',           'Maiquel Gonzalez',        'active'),
    (v_org_id, 'Michael',     'Covinton',           'Michael Covinton',        'active'),
    (v_org_id, 'Fabian',      'Lemus',              'Fabian Lemus',            'active'),
    (v_org_id, 'Rogelio',     'Garcia',             'Rogelio Garcia',          'active'),
    (v_org_id, 'Lazaro',      'Gonzales',           'Lazaro Gonzales',         'active'),
    (v_org_id, 'Jorge',       'Argote',             'Jorge Argote',            'active'),
    (v_org_id, 'Bruce',       'Burrus',             'Bruce Burrus',            'active'),
    (v_org_id, 'Mauricio',    'Arevalo',            'Mauricio Arevalo',        'active'),
    (v_org_id, 'Iran',        'Iznaga Acosta',      'Iran Iznaga Acosta',      'active'),
    (v_org_id, 'Brandon',     'Espinosa',           'Brandon Espinosa',        'active'),
    (v_org_id, 'Francisco',   'Murillo',            'Francisco Murillo',       'active'),
    (v_org_id, 'Lorenzo',     'Gil',                'Lorenzo Gil',             'active'),
    (v_org_id, 'Maria',       'Hernandez',          'Maria Hernandez',         'active'),
    (v_org_id, 'James',       'Jones',              'James Jones',             'active'),
    (v_org_id, 'Ericka',      'Sterling',           'Ericka Sterling',         'active'),
    (v_org_id, 'Daron',       'Curtis',             'Daron Curtis',            'active'),
    (v_org_id, 'Kenneth',     'Trapp',              'Kenneth Trapp',           'active'),
    (v_org_id, 'Jerome',      'Johnson',            'Jerome Johnson',          'active'),
    (v_org_id, 'Richard',     'Morris',             'Richard Morris',          'active'),
    (v_org_id, 'Jacinto',     'Montes',             'Jacinto Montes',          'active'),
    (v_org_id, 'Lazaro',      'Fernandez',          'Lazaro Fernandez',        'active'),
    (v_org_id, 'Yurkielnudis','Cutino',             'Yurkielnudis Cutino',     'active'),
    (v_org_id, 'Isaac',       'Humberto',           'Isaac Humberto',          'active'),
    (v_org_id, 'Noel',        'Malagon Suarez',     'Noel Malagon Suarez',     'active'),
    (v_org_id, 'Israel',      'Javier Ayala',       'Israel Javier Ayala',     'active'),
    (v_org_id, 'Yoel',        'Del Rio',            'Yoel Del Rio',            'active'),
    (v_org_id, 'Leodan',      'Gutierrez',          'Leodan Gutierrez',        'active'),
    (v_org_id, 'Julio',       'Angel Delgado',      'Julio Angel Delgado',     'active'),
    (v_org_id, 'Gary',        'Flowers',            'Gary Flowers',            'active'),
    (v_org_id, 'James',       'Mays',               'James Mays',              'active'),
    (v_org_id, 'Cliff',       'Clark',              'Cliff Clark',             'active'),
    (v_org_id, 'Octavio',     'Sosa',               'Octavio Sosa',            'active'),
    (v_org_id, 'Steven',      'Domina',             'Steven Domina',           'active'),
    (v_org_id, 'Fernando',    'Olivas',             'Fernando Olivas',         'active'),
    (v_org_id, 'Oscar',       'Castro',             'Oscar Castro',            'active'),
    (v_org_id, 'Felino',      'Sierra',             'Felino Sierra',           'active'),
    (v_org_id, 'Israel',      'Melendez',           'Israel Melendez',         'active'),
    (v_org_id, 'Bradley',     'Gardner',            'Bradley Gardner',         'active'),
    (v_org_id, 'Lindsey',     'Gardner',            'Lindsey Gardner',         'active'),
    (v_org_id, 'Anyel',       'Piedra',             'Anyel Piedra',            'active'),
    (v_org_id, 'Richard',     'Fournier',           'Richard Fournier',        'active'),
    (v_org_id, 'Richar',      'Garcia',             'Richar Garcia',           'active'),
    (v_org_id, 'Dayan',       'Chaviano',           'Dayan Chaviano',          'active'),
    (v_org_id, 'Marco',       'Ordonez',            'Marco Ordonez',           'active'),
    (v_org_id, 'Roberto',     'Trueba',             'Roberto Trueba',          'active'),
    (v_org_id, 'Luis',        'Picott',             'Luis Picott',             'active'),
    (v_org_id, 'Roliester',   'Rodriguez',          'Roliester Rodriguez',     'active'),
    (v_org_id, 'Jose',        'Manrique',           'Jose Manrique',           'active'),
    (v_org_id, 'Jhon',        'Diaz',               'Jhon Diaz',               'active'),
    (v_org_id, 'Onelio',      'Leon',               'Onelio Leon',             'active'),
    (v_org_id, 'Andres',      'Gonzalez',           'Andres Gonzalez',         'active'),
    (v_org_id, 'Osmani',      'Venzant',            'Osmani Venzant',          'active'),
    (v_org_id, 'Rene',        'Hernandez',          'Rene Hernandez',          'active'),
    (v_org_id, 'Sayn',        'Mantilla',           'Sayn Mantilla',           'active'),
    (v_org_id, 'Yunior',      'Santana',            'Yunior Santana',          'active'),
    (v_org_id, 'Shawn',       'Harris',             'Shawn Harris',            'active'),
    (v_org_id, 'Marcel',      'Johnson',            'Marcel Johnson',          'active'),
    (v_org_id, 'Hakin',       'Strain',             'Hakin Strain',            'active'),
    (v_org_id, 'Alberto',     'Carreras',           'Alberto Carreras',        'active'),
    (v_org_id, 'Armando',     'Tabares',            'Armando Tabares',         'active'),
    (v_org_id, 'Yaisel',      'Tarrero',            'Yaisel Tarrero',          'active'),
    (v_org_id, 'Roque',       'Albin',              'Roque Albin',             'active'),
    (v_org_id, 'Willie',      'Acosta',             'Willie Acosta',           'active'),
    (v_org_id, 'Jose',        'Miranda',            'Jose Miranda',            'active'),
    (v_org_id, 'Moises',      'Uribe',              'Moises Uribe',            'active'),
    (v_org_id, 'Jorge',       'Escalante',          'Jorge Escalante',         'active'),
    (v_org_id, 'Yadiel',      'Gonzalez',           'Yadiel Gonzalez',         'active'),
    (v_org_id, 'Lazaro',      'Morejon',            'Lazaro Morejon',          'active'),
    (v_org_id, 'Armando',     'Garcia',             'Armando Garcia',          'active'),
    (v_org_id, 'Steven',      'Posso',              'Steven Posso',            'active'),
    (v_org_id, 'Chameka',     'Cloy',               'Chameka Cloy',            'active'),
    (v_org_id, 'Okan',        'Duzce',              'Okan Duzce',              'active'),
    (v_org_id, 'Umut',        'Aydin',              'Umut Aydin',              'active'),
    (v_org_id, 'Sipan',       'Kinis',              'Sipan Kinis',             'active'),
    (v_org_id, 'Ercan',       'Zencir',             'Ercan Zencir',            'active'),
    (v_org_id, 'Gursimran',   'Singh',              'Gursimran Singh',         'active'),
    (v_org_id, 'Gurjot',      'Singh',              'Gurjot Singh',            'active'),
    (v_org_id, 'Nathaniel',   'De Graw',            'Nathaniel De Graw',       'active'),
    (v_org_id, 'Gregorio',    'Cortez',             'Gregorio Cortez',         'active'),
    (v_org_id, 'Edgar',       'Castanon',           'Edgar Castanon',          'active'),
    (v_org_id, 'Carmen',      'Cortez',             'Carmen Cortez',           'active'),
    (v_org_id, 'Emmanuel',    'Banuelos',           'Emmanuel Banuelos',       'active'),
    (v_org_id, 'Daniel',      'De Armas',           'Daniel De Armas',         'active'),
    (v_org_id, 'Antonio',     'Diaz',               'Antonio Diaz',            'active'),
    (v_org_id, 'Jose',        'Marin',              'Jose Marin',              'active'),
    (v_org_id, 'Francisco',   'Davila',             'Francisco Davila',        'active'),
    (v_org_id, 'Orlando',     'Reyes',              'Orlando Reyes',           'active'),
    (v_org_id, 'Ismael',      'Jaber',              'Ismael Jaber',            'active'),
    (v_org_id, 'James',       'Powell',             'James Powell',            'active'),
    (v_org_id, 'Ediberto',    'Silva',              'Ediberto Silva',          'active'),
    (v_org_id, 'Jesus Carlos','Frankeis',           'Jesus Carlos Frankeis',   'active'),
    (v_org_id, 'Nelson',      'Casalas',            'Nelson Casalas',          'active'),
    (v_org_id, 'Reiner',      'Perez',              'Reiner Perez',            'active'),
    (v_org_id, 'Raidel',      'Veliz',              'Raidel Veliz',            'active'),
    (v_org_id, 'Amador',      'Maikel',             'Amador Maikel',           'active'),
    (v_org_id, 'Omar',        'Pacheco',            'Omar Pacheco',            'active'),
    (v_org_id, 'Alejandro',   'Heredia',            'Alejandro Heredia',       'active'),
    (v_org_id, 'Andres',      'Cardona',            'Andres Cardona',          'active'),
    (v_org_id, 'Cesar',       'Cardona',            'Cesar Cardona',           'active')
  ON CONFLICT DO NOTHING;


  -- ─── PIT / PICKUP SITES ──────────────────────────────────────────────
  -- Unique sites only (de-duped)

  INSERT INTO public.pits (organization_id, name, pit_type, status)
  VALUES
    (v_org_id, 'US Aggregates Inc Delphi',              'aggregate_pit',  'active'),
    (v_org_id, 'Pin Drop - Courson',                    'pin_drop',       'active'),
    (v_org_id, 'Ward Stone Tipton',                     'quarry',         'active'),
    (v_org_id, 'TC Red Wine Services',                  'vendor',         'active'),
    (v_org_id, 'Bentz Plant',                           'plant',          'active'),
    (v_org_id, 'BAS Equipment & Trucking Services LLC', 'vendor',         'active'),
    (v_org_id, 'Timberland Quarry',                     'quarry',         'active')
  ON CONFLICT DO NOTHING;


  -- ─── DROP-OFF / DELIVERY SITES ───────────────────────────────────────
  -- Unique drop-off locations only (de-duped)

  INSERT INTO public.pits (organization_id, name, pit_type, status)
  VALUES
    (v_org_id, 'Pin Drop - Domino Delphi',   'pin_drop', 'active'),
    (v_org_id, 'ManCamp Drop off',           'job_site',  'active'),
    (v_org_id, 'Dominio project Tipton',     'job_site',  'active'),
    (v_org_id, 'Pin Drop - RPL 2 Dump',     'pin_drop',  'active'),
    (v_org_id, 'Roman Wind',                 'job_site',  'active')
  ON CONFLICT DO NOTHING;


  RAISE NOTICE 'Ronyx seed complete.';
  RAISE NOTICE '  Owner operators · Trucks · Drivers · Pits / Pickup sites · Drop-off sites';

END $$;


-- ─── Validate ────────────────────────────────────────────────────────────────

SELECT 'owner_operators'  AS entity, COUNT(*) AS rows FROM public.owner_operators
UNION ALL
SELECT 'ronyx_trucks',                COUNT(*)          FROM public.ronyx_trucks
UNION ALL
SELECT 'driver_profiles',             COUNT(*)          FROM public.driver_profiles
UNION ALL
SELECT 'pits',                        COUNT(*)          FROM public.pits
ORDER BY entity;
