import { NextRequest, NextResponse } from "next/server";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { randomBytes } from "crypto";

export const dynamic = "force-dynamic";

// POST — generate (or return existing) QR token for a ticket
export async function POST(
  req: NextRequest,
  { params }: { params: { ticketId: string } }
) {
  try {
    const supabase = createSupabaseServerClient();
    const { ticketId } = params;
    const body = await req.json().catch(() => ({}));
    const createdBy = body.created_by || "office";

    // Check if ticket already has a QR token
    const { data: existing } = await supabase
      .from("aggregate_tickets")
      .select("id, qr_token, qr_url, ticket_number")
      .eq("id", ticketId)
      .single();

    if (!existing) {
      return NextResponse.json({ error: "Ticket not found" }, { status: 404 });
    }

    // Return existing token if present and not forced to regenerate
    if (existing.qr_token && !body.regenerate) {
      return NextResponse.json({
        ticket_id: ticketId,
        qr_token:  existing.qr_token,
        qr_url:    existing.qr_url,
        ticket_number: existing.ticket_number,
        already_existed: true,
      });
    }

    // Generate new secure token
    const token = randomBytes(20).toString("hex"); // 40-char hex = 160-bit entropy
    const appUrl = process.env.NEXT_PUBLIC_APP_URL || "https://ronyx.movearoundtms.app";
    const qrUrl  = `${appUrl}/ronyx/scan?t=${token}`;

    const { error: updateErr } = await supabase
      .from("aggregate_tickets")
      .update({
        qr_token:      token,
        qr_url:        qrUrl,
        qr_created_at: new Date().toISOString(),
        qr_created_by: createdBy,
      })
      .eq("id", ticketId);

    if (updateErr) {
      return NextResponse.json({ error: updateErr.message }, { status: 500 });
    }

    // Audit
    await supabase.from("ticket_audit_log").insert({
      ticket_id:   ticketId,
      action:      "qr_code_generated",
      description: `Fast Scan™ QR code generated by ${createdBy}`,
      metadata:    { qr_token: token, qr_url: qrUrl },
    }).maybeSingle();

    return NextResponse.json({
      ticket_id: ticketId,
      qr_token:  token,
      qr_url:    qrUrl,
      ticket_number: existing.ticket_number,
    });
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : "QR generation failed";
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}

// GET — retrieve current QR info for a ticket
export async function GET(
  _req: NextRequest,
  { params }: { params: { ticketId: string } }
) {
  const supabase = createSupabaseServerClient();
  const { data } = await supabase
    .from("aggregate_tickets")
    .select("id, ticket_number, qr_token, qr_url, qr_created_at, qr_scan_count, last_qr_scanned_at")
    .eq("id", params.ticketId)
    .single();

  if (!data) return NextResponse.json({ error: "Ticket not found" }, { status: 404 });
  return NextResponse.json(data);
}
