"use client";

import { useState } from "react";
import Link from "next/link";

const demoOptions = [
  { id: "docs", label: "SAT Compliance & Document Errors", target: "#demo-docs" },
  { id: "customs", label: "Shipments Stuck in Customs", target: "#demo-customs" },
  { id: "finance", label: "Managing Multi-Currency Payments", target: "#demo-finance" },
];

export default function CrossBorderDemo() {
  const [selectedDemo, setSelectedDemo] = useState("docs");

  return (
    <div className="min-h-screen bg-[#080808] text-white">
      <style jsx global>{`
        @import url("https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=Space+Grotesk:wght@400;600;700;800&display=swap");

        :root {
          --cb-yellow: #ffd700;
          --cb-blue: #00b4ff;
          --cb-red: #ff2800;
          --cb-bg: #080808;
          --cb-card: #141414;
        }

        * {
          box-sizing: border-box;
        }

        body {
          margin: 0;
          font-family: "Inter", sans-serif;
          background: var(--cb-bg);
        }

        h1,
        h2,
        h3 {
          font-family: "Space Grotesk", sans-serif;
        }
      `}</style>

      <header className="sticky top-0 z-40 border-b border-white/10 bg-[#080808]/95 backdrop-blur">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-4">
          <Link href="/" className="text-lg font-bold tracking-tight text-white">
            MoveAround TMS
          </Link>
          <div className="flex items-center gap-3 text-xs uppercase tracking-widest text-white/60">
            <span>Cross-Border Demo</span>
            <span className="h-1 w-1 rounded-full bg-[#ffd700]"></span>
            <span>US ↔ MX</span>
          </div>
        </div>
      </header>

      <section className="px-6 pb-16 pt-24">
        <div className="mx-auto max-w-6xl">
          <div className="inline-flex items-center gap-2 rounded-full border border-[#ffd700]/40 bg-[#ffd700]/10 px-4 py-2 text-xs font-semibold uppercase tracking-wider text-[#ffd700]">
            Cross-Border Command Center
          </div>
          <h1 className="mt-6 text-4xl font-bold text-white md:text-5xl">
            Stop the Customs Panic. Start the Automated Clearance.
          </h1>
          <p className="mt-4 max-w-3xl text-lg text-white/80">
            The first all-in-one platform that automates Mexican compliance, provides live customs visibility,
            and unifies US-MX operations—turning your biggest risk into a competitive advantage.
          </p>

          <div className="mt-10 grid gap-6 rounded-2xl border border-white/10 bg-[#141414] p-6 md:grid-cols-[1.2fr_1fr]">
            <div>
              <h2 className="text-2xl font-semibold text-white">What keeps you up at night?</h2>
              <p className="mt-2 text-sm text-white/70">
                Select your biggest compliance pain and jump to a tailored demo module.
              </p>
              <div className="mt-6 grid gap-3">
                {demoOptions.map((option) => (
                  <button
                    key={option.id}
                    onClick={() => {
                      setSelectedDemo(option.id);
                      const el = document.querySelector(option.target);
                      if (el) {
                        el.scrollIntoView({ behavior: "smooth", block: "start" });
                      }
                    }}
                    className="flex items-center justify-between rounded-xl border border-white/10 bg-[#1b1b1b] px-4 py-3 text-left text-sm text-white/90 transition hover:border-[#ffd700]/60"
                  >
                    <span>{option.label}</span>
                    <span className="text-xs uppercase text-[#ffd700]">View</span>
                  </button>
                ))}
              </div>
            </div>

            <div className="rounded-xl border border-[#00b4ff]/30 bg-[#0f1a22] p-5">
              <h3 className="text-lg font-semibold text-white">Compliance Guarantee</h3>
              <p className="mt-2 text-sm text-white/70">
                If a load is delayed or fined due to a documentation error generated by our system, we credit
                you <strong>3x the monthly module fee</strong> and cover the fine up to $5,000.
              </p>
              <p className="mt-4 text-xs text-white/50">
                Terms apply. Covers auto-generated CFDI 4.0 & Carta Porte documents.
              </p>
              <a
                href="mailto:sales@movearoundtms.com"
                className="mt-6 inline-flex w-full items-center justify-center rounded-lg bg-[#ffd700] px-4 py-3 text-sm font-semibold text-black"
              >
                Book Compliance Demo
              </a>
            </div>
          </div>
        </div>
      </section>

      <section className="px-6 pb-20">
        <div className="mx-auto max-w-6xl space-y-8">
          <div id="demo-docs" className="rounded-2xl border border-white/10 bg-[#141414] p-6">
            <div className="flex flex-wrap items-center justify-between gap-4">
              <h3 className="text-2xl font-semibold text-white">Flawless Document Automation</h3>
              <span className="rounded-full bg-[#ffd700]/10 px-3 py-1 text-xs font-semibold uppercase text-[#ffd700]">
                75s Demo
              </span>
            </div>
            <p className="mt-2 text-sm text-white/70">
              Auto-generate CFDI 4.0, Carta Porte, and US Bill of Lading from one load screen.
            </p>
            <div className="mt-5 grid gap-4 md:grid-cols-3">
              {[
                {
                  title: "Problem",
                  body:
                    "Clerk jumps between 5 windows (TMS, PDFs, SAT portal, Excel) and still risks errors.",
                },
                {
                  title: "Solution",
                  body:
                    "Enter load data once. MoveAround produces compliant CFDI 4.0 + Carta Porte instantly.",
                },
                {
                  title: "Result",
                  body:
                    "All docs bundled, emailed to broker/driver/client with a SAT compliant checkmark.",
                },
              ].map((step) => (
                <div key={step.title} className="rounded-xl border border-white/10 bg-[#1b1b1b] p-4">
                  <h4 className="text-sm font-semibold text-[#ffd700]">{step.title}</h4>
                  <p className="mt-2 text-sm text-white/70">{step.body}</p>
                </div>
              ))}
            </div>
            <a
              href="mailto:sales@movearoundtms.com"
              className="mt-6 inline-flex items-center rounded-lg bg-[#ffd700] px-4 py-2 text-sm font-semibold text-black"
            >
              Book a Demo to Automate Documentation
            </a>
          </div>

          <div id="demo-customs" className="rounded-2xl border border-white/10 bg-[#141414] p-6">
            <div className="flex flex-wrap items-center justify-between gap-4">
              <h3 className="text-2xl font-semibold text-white">Live Customs Visibility</h3>
              <span className="rounded-full bg-[#00b4ff]/10 px-3 py-1 text-xs font-semibold uppercase text-[#00b4ff]">
                60s Demo
              </span>
            </div>
            <p className="mt-2 text-sm text-white/70">
              Track every shipment status in one portal: Pre‑Check, In Review, Released.
            </p>
            <div className="mt-5 grid gap-4 md:grid-cols-3">
              {[
                {
                  title: "Problem",
                  body: "Truck stuck at Laredo with “Status Unknown” and endless broker calls.",
                },
                {
                  title: "Solution",
                  body: "Customs dashboard shows Load #8052 in SAT Pre‑Check with ETA.",
                },
                {
                  title: "Result",
                  body: "Status flips to Released; SMS alerts go to dispatcher, customer, driver.",
                },
              ].map((step) => (
                <div key={step.title} className="rounded-xl border border-white/10 bg-[#1b1b1b] p-4">
                  <h4 className="text-sm font-semibold text-[#00b4ff]">{step.title}</h4>
                  <p className="mt-2 text-sm text-white/70">{step.body}</p>
                </div>
              ))}
            </div>
            <a
              href="mailto:sales@movearoundtms.com"
              className="mt-6 inline-flex items-center rounded-lg bg-[#00b4ff] px-4 py-2 text-sm font-semibold text-black"
            >
              Book a Demo for Customs Tracking
            </a>
          </div>

          <div id="demo-finance" className="rounded-2xl border border-white/10 bg-[#141414] p-6">
            <div className="flex flex-wrap items-center justify-between gap-4">
              <h3 className="text-2xl font-semibold text-white">Unified Financial & Audit Hub</h3>
              <span className="rounded-full bg-[#ff2800]/10 px-3 py-1 text-xs font-semibold uppercase text-[#ff2800]">
                60s Demo
              </span>
            </div>
            <p className="mt-2 text-sm text-white/70">
              Multi‑currency billing with audit‑ready compliance logs in one place.
            </p>
            <div className="mt-5 grid gap-4 md:grid-cols-3">
              {[
                {
                  title: "Problem",
                  body: "Spreadsheets for USD/MXN, exchange rates, and “Paid?” chaos.",
                },
                {
                  title: "Solution",
                  body: "Billing hub shows USD + MXN invoices and SAT audit trail per load.",
                },
                {
                  title: "Result",
                  body: "Generate audit packet ZIP in seconds. Close books faster.",
                },
              ].map((step) => (
                <div key={step.title} className="rounded-xl border border-white/10 bg-[#1b1b1b] p-4">
                  <h4 className="text-sm font-semibold text-[#ff2800]">{step.title}</h4>
                  <p className="mt-2 text-sm text-white/70">{step.body}</p>
                </div>
              ))}
            </div>
            <a
              href="mailto:sales@movearoundtms.com"
              className="mt-6 inline-flex items-center rounded-lg bg-[#ff2800] px-4 py-2 text-sm font-semibold text-white"
            >
              Book a Demo for Cross‑Border Finance
            </a>
          </div>
        </div>
      </section>

      <section className="px-6 pb-24">
        <div className="mx-auto max-w-6xl rounded-2xl border border-white/10 bg-[#141414] p-8 text-center">
          <h2 className="text-3xl font-semibold text-white">
            Schedule Your Cross‑Border Strategy Briefing
          </h2>
          <p className="mt-3 text-sm text-white/70">
            We’ll audit your compliance workflow, map US‑MX handoffs, and deliver a custom risk‑reduction report.
          </p>
          <a
            href="mailto:sales@movearoundtms.com"
            className="mt-6 inline-flex items-center rounded-lg bg-[#ffd700] px-6 py-3 text-sm font-semibold text-black"
          >
            Schedule My Free Border Strategy Briefing
          </a>
        </div>
      </section>
    </div>
  );
}
