import MarketingShell from "../components/MarketingShell";

export default function CrossBorderPage() {
  return (
    <MarketingShell
      eyebrow="Cross-Border Command Center"
      title="Stop the Customs Panic. Start Automated Clearance."
      subtitle="Automate SAT compliance, track customs status live, and unify US-MX operations."
      ctaText="See the Cross-Border Demo"
      ctaHref="/demo/cross-border"
    >
      <section className="marketing-grid">
        {[
          {
            title: "Flawless Document Automation",
            body: "Auto-generate CFDI 4.0, Carta Porte, and US docs from load data with zero re-entry.",
          },
          {
            title: "Live Customs Visibility",
            body: "Track every load: Pre‑Check, In Review, Released, with proactive hold alerts.",
          },
          {
            title: "Unified Financials",
            body: "Invoice in USD/MXN with locked exchange rates and a single AR dashboard.",
          },
          {
            title: "Immutable Audit Trail",
            body: "Every document and status update is logged and stored for instant audits.",
          },
        ].map((item) => (
          <div key={item.title} className="marketing-card">
            <h3>{item.title}</h3>
            <p>{item.body}</p>
          </div>
        ))}
      </section>

      <section className="marketing-section">
        <div className="marketing-card">
          <h3>MoveAround Cross-Border Guarantee</h3>
          <p>
            If a load is delayed or fined due to a documentation error generated by our system,
            we credit 3x the monthly module fee and cover the fine up to $5,000. Terms apply.
          </p>
        </div>
      </section>
    </MarketingShell>
  );
}
"use client";

import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";

export default function CrossBorderAutomationPage() {
  const [enabled, setEnabled] = useState(false);
  const [loading, setLoading] = useState(true);
  const demoMode = process.env.NEXT_PUBLIC_DEMO_MODE === "true";

  useEffect(() => {
    loadStatus();
  }, []);

  async function loadStatus() {
    setLoading(true);
    try {
      const res = await fetch("/api/cross-border/status", { cache: "no-store" });
      const data = await res.json();
      setEnabled(Boolean(data.enabled));
    } catch (error) {
      console.error("Failed to load cross-border status", error);
    } finally {
      setLoading(false);
    }
  }

  async function toggleEnabled() {
    const next = !enabled;
    setEnabled(next);
    await fetch("/api/cross-border/status", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ enabled: next }),
    });
  }

  return (
    <div className="min-h-screen bg-space-deep p-8">
      <div className="max-w-4xl mx-auto space-y-6">
        <div>
          <h1 className="text-2xl font-medium text-text-primary uppercase tracking-wider">
            Cross-Border Automation
          </h1>
          <p className="text-text-secondary text-sm mt-1">
            Streamline US–Mexico documentation and compliance workflows.
          </p>
        </div>

        {demoMode && (
          <div className="p-4 rounded border border-orange-400 bg-orange-50 text-orange-700 text-sm">
            Demo mode is enabled. Changes are not saved.
          </div>
        )}

        <Card className="bg-space-panel border-space-border">
          <CardHeader className="border-b border-space-border">
            <CardTitle className="text-text-primary text-sm uppercase tracking-wider">
              Mexico Compliance
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-6 flex items-center justify-between">
            <div>
              <div className="text-text-primary font-medium">
                CFDI 4.0 + Carta Porte 3.0
              </div>
              <div className="text-text-secondary text-xs">
                Enable automation for cross-border document readiness.
              </div>
            </div>
            <Button onClick={toggleEnabled} disabled={demoMode || loading}>
              {enabled ? "Enabled" : "Enable"}
            </Button>
          </CardContent>
        </Card>

        <Card className="bg-space-panel border-space-border">
          <CardHeader className="border-b border-space-border">
            <CardTitle className="text-text-primary text-sm uppercase tracking-wider">
              Cross-Border Checklist
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-6 space-y-3 text-text-secondary text-sm">
            <div>✅ Validate carrier DOT/MC for cross-border lanes</div>
            <div>✅ Ensure Carta Porte fields are complete</div>
            <div>✅ Confirm CFDI receiver and tax regime</div>
            <div>✅ Track customs handoff timestamps</div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
