import MarketingShell from "../components/MarketingShell";

export default function CrossBorderPage() {
  return (
    <MarketingShell
      eyebrow="Cross-Border Command Center"
      title="Stop the Customs Panic. Start Automated Clearance."
      subtitle="Automate SAT compliance, track customs status live, and unify US-MX operations."
      ctaText="See the Cross-Border Demo"
      ctaHref="/demo/cross-border"
    >
      <section className="marketing-grid">
        {[
          {
            title: "Flawless Document Automation",
            body: "Auto-generate CFDI 4.0, Carta Porte, and US docs from load data with zero re-entry.",
          },
          {
            title: "Live Customs Visibility",
            body: "Track every load: Pre‑Check, In Review, Released, with proactive hold alerts.",
          },
          {
            title: "Unified Financials",
            body: "Invoice in USD/MXN with locked exchange rates and a single AR dashboard.",
          },
          {
            title: "Immutable Audit Trail",
            body: "Every document and status update is logged and stored for instant audits.",
          },
        ].map((item) => (
          <div key={item.title} className="marketing-card">
            <h3>{item.title}</h3>
            <p>{item.body}</p>
          </div>
        ))}
      </section>

      <section className="marketing-section">
        <div className="marketing-card">
          <h3>MoveAround Cross-Border Guarantee</h3>
          <p>
            If a load is delayed or fined due to a documentation error generated by our system,
            we credit 3x the monthly module fee and cover the fine up to $5,000. Terms apply.
          </p>
        </div>
      </section>
    </MarketingShell>
  );
}
